/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MakingChaiImport } from './routes/making-chai'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MakingChaiRoute = MakingChaiImport.update({
  id: '/making-chai',
  path: '/making-chai',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/making-chai': {
      id: '/making-chai'
      path: '/making-chai'
      fullPath: '/making-chai'
      preLoaderRoute: typeof MakingChaiImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/making-chai': typeof MakingChaiRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/making-chai': typeof MakingChaiRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/making-chai': typeof MakingChaiRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/making-chai'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/making-chai'
  id: '__root__' | '/' | '/making-chai'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MakingChaiRoute: typeof MakingChaiRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MakingChaiRoute: MakingChaiRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/making-chai"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/making-chai": {
      "filePath": "making-chai.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
